### ISSUE TITLE
Sentinel-1 alias `reader.datatree` not aligned with `reader.dt`

### ISSUE THREAD

**Issue by agrouaze** [umr-lops/xsar#165]
command to reproduce:
```bash
L1B_xspectra_EW_SLC_IFR --tiff /home/datawork-cersat-public/project/mpc-sentinel1/data/esa/sentinel-1b/L1/EW/S1B_EW_SL2__1_/2021/247/S1B_EW_SL2__1_DV_20210904T085204_20210904T085311_028546_036818_AEBD.SAFE/measurement/s1b-ew2-slc-vv-20210904t085204-20210904t085308-028546-036818-007.tiff --outputdir /tmp/ --version 2.5 --xspeconfigname tiles20km
```

traceback:
```python
debug SL2 S1B_EW_SL2__1_DV_20210904T085204_20210904T085311_028546_036818_AEBD.SAFE /home/datawork-cersat-public/project/mpc-sentinel1/data/esa/sentinel-1b/L1/EW/S1B_EW_SL2__1_/2021/247/S1B_EW_SL2__1_DV_20210904T085204_20210904T085311_028546_036818_AEBD.SAFE SENTINEL1_DS:S1B_EW_SL2__1_DV_20210904T085204_20210904T085311_028546_036818_AEBD.SAFE:EW2
Traceback (most recent call last):
  File "/opt/conda-envs/dev/bin/L1B_xspectra_EW_SLC_IFR", line 8, in <module>
    sys.exit(main())
  File "/home1/datahome/agrouaze/sources/git/xsar_slc/xsarslc/scripts/L1B_xspectra_EW_SLC_IFR.py", line 172, in main
    generate_EW_L1Bxspec_product(slc_ew_path=slc_ew_path, output_filename=output_filename,
  File "/home1/datahome/agrouaze/sources/git/xsar_slc/xsarslc/scripts/L1B_xspectra_EW_SLC_IFR.py", line 60, in generate_EW_L1Bxspec_product
    bu = xsar.Sentinel1Meta(str_gdal)._bursts
  File "/home1/datahome/agrouaze/sources/git/xsar/src/xsar/utils.py", line 94, in wrapper
    result = f(*args, **kwargs)
  File "/home1/datahome/agrouaze/sources/git/xsar/src/xsar/sentinel1_meta.py", line 72, in __init__
    print('dt init (from datatree method)',dt)
NameError: name 'dt' is not defined
```

**Comment by agrouaze** [comment]
closed with https://github.com/umr-lops/xarray-safe-s1/pull/6
